<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>false</UseWindowsForms>
    <ImportWindowsDesktopTargets>false</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>MotoMond</AssemblyTitle>
    <Product>MotoMond</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.Data.OracleClient" />
    <Reference Include="System.Drawing.Design" />
    <Reference Include="System.Net" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System.Transactions" />
    <Reference Include="System.Web" />
    <Reference Include="System.Windows" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="MototrboModels.json" />
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Moto.Net.RPC\Moto.Net.RPC.csproj" />
    <ProjectReference Include="..\Moto.Net\Moto.Net.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle" Version="1.8.9" />
    <PackageReference Include="CsvHelper" Version="27.2.1" />
    <PackageReference Include="Google.Protobuf" Version="3.20.0" />
    <PackageReference Include="InfluxDB.Client" Version="4.0.0" />
    <PackageReference Include="InfluxDB.Client.Core" Version="4.0.0" />
    <PackageReference Include="JsonSubTypes" Version="1.8.0" />
    <PackageReference Include="K4os.Compression.LZ4" Version="1.2.16" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.2.16" />
    <PackageReference Include="K4os.Hash.xxHash" Version="1.0.7" />
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Version="8.0.11" />
    <PackageReference Include="MySql.Data" Version="8.0.28" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NodaTime" Version="3.0.10" />
    <PackageReference Include="NodaTime.Serialization.JsonNet" Version="3.0.0" />
    <PackageReference Include="PcapDotNet" Version="0.10.2" />
    <PackageReference Include="RabbitMQ.Client" Version="6.2.4" />
    <PackageReference Include="RestSharp" Version="107.3.0" />
    <PackageReference Include="SSH.NET" Version="2020.0.2" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.0" />
    <PackageReference Include="System.Security.Permissions" Version="8.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>
</Project>